package com.android.fileTranser;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;

import com.jacob.activeX.ActiveXComponent;
import com.jacob.com.ComThread;
import com.jacob.com.Dispatch;
import com.android.fileTranser.PropertiesUtil;

/**
 * 
 * @author LiDSXpTst
 */
public class Jjmain {

	/** Creates new form Jjmain */
	public Jjmain() {

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" 生成的代码
	// ">//GEN-BEGIN:initComponents
	static final long DAYS_BETWEEN_18991230_AND_19700101 = 25569;
	static final long MILLISECONDS_PER_DAY = 86400000;

	public static double javaTimeToDelphiTime(final Date time) {
		return (time.getTime() + DAYS_BETWEEN_18991230_AND_19700101
				* MILLISECONDS_PER_DAY)
				/ (double) MILLISECONDS_PER_DAY;
	}

	public static Date delphiTimeToJavaTime(final double time) {
		long millis = (long) ((time - DAYS_BETWEEN_18991230_AND_19700101) * MILLISECONDS_PER_DAY);
		// 再轉一次，消除誤差
		double delphiTime = (millis + DAYS_BETWEEN_18991230_AND_19700101
				* MILLISECONDS_PER_DAY)
				/ (double) MILLISECONDS_PER_DAY;
		millis = (long) ((delphiTime - DAYS_BETWEEN_18991230_AND_19700101) * MILLISECONDS_PER_DAY);
		millis = millis - 8 * 3600 * 1000;// 减八小时
		return new Date(millis);
	}

	public String getDocPath(String sDocID, String sDocKey, String DiskNo,
			String tempdisk) { // /主调用
		long lv = Long.valueOf(sDocKey).longValue();
		double dv = Double.longBitsToDouble(lv);
		Date dt = delphiTimeToJavaTime(dv);
		//SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy/MM/dd/HH/mm/ss/");		
		SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy/MM/dd/HH/mm/ss/");
		sdf.setTimeZone(TimeZone.getTimeZone("GMT+08:00"));
		String rst = sdf.format(dt);
		
		tempdisk = tempdisk.trim();
		// tempdisk = tempdisk.replace("\\", "/");
		String tempstr = tempdisk.substring(tempdisk.length() - 1, tempdisk
				.length());
		if (!tempstr.equals("/")) {
			tempstr = tempstr + "/";
			tempdisk = tempdisk.substring(0, tempdisk.length() - 1) + tempstr;
		}
		// tempdisk=tempdisk.replace("\\", "/");

		return tempdisk + "/" + rst + "DocID_" + sDocID + "/";// 有部分写死，需要读配置文件
	};
	
	public String[] getDocInfo(String sDocID, String sDocKey, String DiskNo,
			String tempdisk) { // /主调用
		long lv = Long.valueOf(sDocKey).longValue();
		double dv = Double.longBitsToDouble(lv);
		Date dt = delphiTimeToJavaTime(dv);
		//SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy/MM/dd/HH/mm/ss/");
		SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy/MM/dd/HH/mm/ss/");
		sdf.setTimeZone(TimeZone.getTimeZone("GMT+08:00"));
		String rst = sdf.format(dt);
		String disk=PropertiesUtil.getProp("config.properties","disk"+DiskNo)+ "/" + rst + "DocID_" + sDocID + "/";
		if("0".equals(isExist(disk))){
			rst =getNabTest(sDocKey);
		}		
		tempdisk = tempdisk.trim();
		// tempdisk = tempdisk.replace("\\", "/");
		String tempstr = tempdisk.substring(tempdisk.length() - 1, tempdisk
				.length());
		if (!tempstr.equals("/")) {
			tempstr = tempstr + "/";
			tempdisk = tempdisk.substring(0, tempdisk.length() - 1) + tempstr;
		}
		// tempdisk=tempdisk.replace("\\", "/");
		String[] arr=new String[2];
		arr[0]=tempdisk + "/" + rst + "DocID_" + sDocID + "/";
		arr[1]=rst + "DocID_" + sDocID + "/"; 
		return arr;
	};

	
	/**
	 * 修改原来java日期和delphi日期转换不一致的问题。
	 * 直接调用ocx控件返回一个图片的路径，保证浏览和查看图片时统一路径
	 * where:barcode对应的key值
	 * GetPathByKey：ocx接口方法
	 * 调用方式
	 * 1：在工程中导入 jacob.jar 这个包
	 * 2：把 jacob.dll 拷贝到 服务器jdk\bin目录下
	 */
	Object o= new Object();
	public  String getNabTest(String where){
		String returnStr ="";
		synchronized(o){
			//初始化
			//Key:&nbsp&nbsp<input name=DocKey value='4675835867737556737'>
			//<input type=button name=btn_GetPathByKey value='获取路径' onclick='DocOpe(16)'>
			ActiveXComponent comx = new ActiveXComponent("DocCenterClt.DocCenterClientObj");
			Dispatch ob = (Dispatch) comx.getObject();
		    //调用空间方法，参数调用多个参数依次类推，注意在传递参数前，将Java中的参数转换成Variant
			returnStr = Dispatch.call(ob, "GetPathByKey",where).getString();
			System.out.println("开始调用销毁。..");
			Dispatch.call(ob, "Unini","");
			ComThread.Release();
		}
	    return returnStr;	    
	 }
	public String  isExist(String path) {
		
		  String ise="0";
		  File file = new File(path);
		  //判断文件夹是否存在,如果不存在则创建文件夹
		  if (file.exists()) {
			  ise="1";
		  }
		  return ise;
	}
	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		Date time = new Date();
		System.out.println("javaTimeToDelphiTime="+javaTimeToDelphiTime(time));
		System.out.println("delphiTimeToJavaTime="+delphiTimeToJavaTime(javaTimeToDelphiTime(time)));
		System.out.println(new Jjmain().getDocPath("11", "4676080123659994778", "A0", "http://127.0.0.1:6600/display"));
		double value = javaTimeToDelphiTime(new Date());
		System.out.println(value);
		System.out.println(Double.doubleToLongBits(value));
		System.out.println(new Jjmain().getDocPath("11", ""+Double.doubleToLongBits(value), "A0", "http://127.0.0.1:6600/display"));
		System.out.println(new Jjmain().getDocPath("11", "4676078698617912761", "A0", "http://127.0.0.1:6600/display"));
	}
	protected void finalize() {
	}
}
